### ISSUE TITLE
Connection to 'ssl://pecl.php.net:443' failed: Unable to find the socket transport "ssl"

### ISSUE THREAD

**Issue by bodsch** [lazyfrosch/docker-icingaweb2#1]
When you have similar problems with pecl like this
```
WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update
Could not download from "https://pecl.php.net/get/yaml-2.0.4.tgz", cannot download "pecl/yaml" (Connection to `ssl://pecl.php.net:443' failed: Unable to find the socket transport "ssl" - did you forget to enable it when you configured PHP?)
Error: cannot download "pecl/yaml"
```
`pecl` calls `php` with the `-n` switch, so it does not read `php.ini`.

Small step for debugging:
```
/ # php -i | grep "Registered Stream Socket Transports"
Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, tls, tlsv1.0, tlsv1.1, tlsv1.2

/ # php -ni | grep "Registered Stream Socket Transports"
Registered Stream Socket Transports => tcp, udp, unix, udg
```
A quick (but evil) hack to fix the problem is a one-liner:
`  sed -i 's|$PHP -C -n -q |$PHP -C -q |' /usr/bin/pecl`

Best regards from Hamburg

**Comment by lazyfrosch** [comment]
Amazing... Thanks for the notice! :heart_eyes:

**Comment by toohamster** [comment]
thanks

**Comment by mean-cj** [comment]
solve.
`RUN wget http://curl.haxx.se/ca/cacert.pem --directory-prefix=/usr/local/etc
RUN pecl channel-update pecl.php.net  `

**Comment by lazyfrosch** [comment]
If you pull the current alpine image before hand the certificates should be fine!
