### ISSUE TITLE
Rebase container on top of upstream PHP

### ISSUE THREAD

**Issue by J0WI** [lazyfrosch/docker-icingaweb2#2]
The current image installs PHP from Alpine, which is not recommend for Docker. How about using the [upstream PHP](https://hub.docker.com/_/php) container? It supports PHP as Apache module, or a FPM variant running on Debian or Alpine (can still be linked to [nginx](https://hub.docker.com/_/nginx)).

**Comment by lazyfrosch** [comment]
Well of course it could be, on the other side I'm mainly using it for my development.
